name: color_iq_utils
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.0-93.1.beta

# Add regular dependencies here.
dependencies:
  material_color_utilities: ^0.13.0
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
