name: coloriq_flutter_adaptor
description: Pure Dart color adaptor for Flutter.
version: 0.0.1
publish_to: none
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  color_iq_utils:
    path: ../
  meta: ^1.15.0
  http: ^1.6.0
  html: ^0.15.6

dependency_overrides:
  material_color_utilities: ^0.13.0